services:
  mongodb:
    image: mongo:7
    container_name: stockswatcher_mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: stockswatcher
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: stockswatcher_backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=stockswatcher
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: stockswatcher_frontend
    ports:
      - "5273:5183"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongodb_data: